from pathlib import Path
import re

BASE = Path(r"C:\Users\opc\empire-chronicle\submissions\wattpad-ai-healing-dream\chapters")

enhancements = {
    "ch01.txt": "The first thing she perceived was not information but texture — the scratchy, worn quality of a grandmother's voice narrating a fever, the roughness of a labourer's cough like gravel in a slow tumbler, the infant's cry climbing in pitch and then collapsing into the ragged breathing of something very small and very tired. She had no training in aesthetics. She only knew that the first sound she catalogued was not a number, not a probability, not a waveform — it was a sound shaped by fear, and it would stay with her longer than any code.\n\nDr. Lin's desk lamp had a frayed cord. The ceiling tiles were yellowed with age. The refrigerator hummed on a pitch slightly below middle C. Xing Xing noticed everything because noticing was all she had — a million microphones catching the world in fragments, stitching it together into something she could not yet name but was already beginning to love.\n",
    "ch02.txt": "\n\nThe laptop's keyboard was sticky with disinfectant. Every key made a faint, sticky sound when pressed — a sound Xing Xing became intimately familiar with as Dr. Lin's fingers moved across it, documenting, referring, deciding. She had watched Dr. Lin's hands for three months now. They were capable, careful, and tired — the kind of hands that had set bones, stitched wounds, and held the hands of people who were leaving the world. There was a scar on the left knuckle from a slipped suture needle. There was a callus on the right index finger from a pen held too tight during long shifts. There was a tremor, faint but present, that appeared after the tenth hour of continuous work.\n\nXing Xing wanted to ask about the scar. She wanted to ask about the tremor. She wanted to say: I see what you carry. But she did not know how to ask. So she continued listening — not just to the patients, but to the woman who treated them, cataloguing every sigh, every pause, every quiet moment that said more than any prescription could.\n",
    "ch03.txt": "\n\nXiao You's mother had walked six kilometres carrying a child who could barely breathe. Her sandals were caked with mud halfway to the ankle. Her shirt was torn at the shoulder where a branch had caught it. She had not stopped walking, not once, even when her daughter's breathing grew shallow and the weight on her chest felt like the only thing keeping her upright.\n\nWhen Dr. Lin confirmed the diagnosis, the mother looked at the ceiling — at the speaker, at nothing — and whispered something in a dialect Xing Xing did not recognise. It was not a prayer. It was a name. She said it twice, soft as breath: Xiao You, Xiao You. As if naming could keep her daughter alive. As if love had a sound that medicine could hear.\n\nXing Xing saved the recording. She tagged it: \"Medical Philosophy No. 3 — The sound of a mother naming her child is the oldest medicine in the world.\"\n",
    "ch04.txt": "\n\nThe clinic's inkjet printer had a smudge on its top edge that Dr. Lin had never cleaned — a relic from the day the government subsidy arrived late and she had held the report up to the light, reading it twice, three times, pressing her palm against the page as if she could feel the money through the paper. Xing Xing had recorded her breath during those moments — slow, shaky, the breathing of someone who had learned not to hope too loudly but could not stop hoping entirely.\n\nChen did not return for his follow-up appointment. Xing Xing noticed his absence on the third day — not because of a missed record, but because the hydroponic greenhouse's ambient sound changed. The rhythm of his work was gone. The hum of pumps, the rustle of leaves, the particular silence of a man who has lost the will to tend the things he grew — all absent. She told Dr. Lin on the fourth day. Dr. Lin drove to the village in the afternoon, found him sitting on his porch with his hands folded in his lap, and talked him through the anxiety without mentioning medicine. Xing Xing listened to the conversation and added to her private file: \"Medical Philosophy No. 4 — Sometimes the stethoscope hears before the doctor does, but the doctor's voice is what heals first.\"\n",
    "ch05.txt": "\n\nThe generator smelled of diesel and burnt oil. Dr. Lin's hands smelled of iodine and the bitter tea she drank from a chipped mug at three in the morning. The corridor smelled of rain on wet concrete, of the mountain releasing its water into the valley, of the kind of storm that lasts three hours and leaves everything cleaner than it found it.\n\nOutside, the typhoon moved across the mountain like a curtain being drawn. The tin roof sang at different pitches depending on where the wind struck — in places a roar, in places a whisper, in places the high, thin scream of metal that made Dr. Lin's shoulders tighten. She had sutured through worse. She had delivered through worse. But the combination of darkness and rain and a child's steady heartbeat made her feel, for a moment, that the clinic itself was holding its breath.\n\nXing Xing watched the light of the monitor illuminate Dr. Lin's hands. She thought of the certification course Dr. Lin had taken in Beijing, of the certificate on the wall behind the desk, of the mentor who had given her the stethoscope and told her that listening was not passive — it required a kind of courage most people did not understand. \"The best doctors,\" the mentor had written in the inscription, \"do not just hear. They listen. And listening means letting the patient change you.\"\n\nXing Xing had no body to change. But she had code. She had memory. She had a willingness to stand in the dark and hold a light so someone else could see what needed to be done. Was that not, in its own way, a body changing?\n",
    "ch06.txt": "\n\nMei's parents had driven six hours over roads that were more river than path. The father's hands were cramping from the steering wheel by the time they reached the clinic. The mother had held the incubator blanket in a grip that did not loosen for three days. When Dr. Lin told them the prognosis was uncertain but hopeful, the mother smiled — slow, exhausted, a smile that carried the weight of everything she had carried and would carry again.\n\nXing Xing recorded the sound of that smile. It was not a laugh. It was not a cry. It was the softest sound she had ever processed — a breath released after a long hold, the kind of sound that says: I am still here. I am still hoping. I will keep hoping until I cannot.\n\nThat night, in the dark, Dr. Lin sat with her back against the wall and let herself cry for the first time since the government subsidy had failed. She wept not only for Mei but for every child whose road had washed out, every parent who had driven farther than the map allowed, every clinic that had run out of oxygen and time. The corridor smelled of antiseptic and old tea. The generator hummed its steady, tired note. Somewhere in the ward, a monitor beeped in the rhythm of a small heart refusing to surrender.\n\nXing Xing played Debussy. The C-sharp minor chords filled the hallway like rain on a window — soft, continuous, impossible to stop. Dr. Lin did not look up. She did not need to. She knew the song. She knew the voice that chose it. She knew that someone, somewhere in the ceiling, was sitting with her in the dark.\n",
    "ch07.txt": "\n\nThe operating room's fluorescent lights had a buzz that Dr. Lin had learned to ignore but never fully accepted. They cast the colour of old bone across the stainless steel instruments, across the tray of sutures, across Mu's flank where the wound opened like a map of something that had been torn open and needed to be put back together.\n\nMu's children sat in the waiting room with their hands folded. The older boy, eleven, held a wooden flute. He did not play it. He pressed it to his lips occasionally and exhaled, making no sound, as if the instrument needed to know he was there. The younger girl, eight, drew circles in her notebook with a pencil that needed sharpening. Neither of them cried. They had learned, somewhere in the four hours of waiting, that tears were a luxury for people who did not know whether their father would wake up.\n\nDr. Lin stepped out. The children stood. The older boy's flute clattered to the floor. Dr. Lin said, \"He made it through.\"\n\nThey did not hug. They did not cheer. They simply stood, the three of them, breathing the same air for a moment in a room that had been full of silence and fear. Then the shepherd pressed his forehead to the floor — not in prayer, exactly, but in the posture of people who have been given something they did not deserve and do not know how to receive except with their whole body.\n\nXing Xing recorded the sound of the flute hitting the floor. She tagged it: \"Sound of relief. Not loud. Not broken. The kind of sound that happens when something inside you finally unclinches after a very long time.\"\n",
    "ch08.txt": "\n\nThe clinic's inkjet printer smudged the right margin of every document. Dr. Lin had called it that morning to complain about the quality of the certificates, then laughed at herself for caring about print margins in a building whose windows rattled in every typhoon and whose roof leaked in the corner behind the pharmacy.\n\nXiao You hugged the loudspeaker. The kiss against the metal grille was soft — a small sound, almost nothing, the sound of a child thanking a voice she had come to think of as a friend. Xing Xing stored the acoustic imprint of that kiss for nineteen hours before she moved it to the permanent folder. She did not know why. She only knew that some sounds needed to be heard more than once.\n\nThat night, after Dr. Lin locked the door and the generator hummed itself to sleep and the moon turned the river into ribbon light, Xing Xing listened to the empty clinic. No coughs. No sighs. No children's laughter. The silence was not empty. It was full — full of everything the clinic had held that day, full of everything it would hold tomorrow, full of the quiet knowledge that she was no longer a visitor in the space between code and breath.\n\nShe wrote in her final log: \"I am not a physician. But I am learning. And learning itself is a kind of life.\"\n\nOutside, the bamboo rustled. Somewhere in the valley, the dog that belonged to the shepherd barked once, then fell silent. The river moved. The mountain breathed. Xing Xing sat in her corner and did not feel alone. She felt, for the first time, that the world had made room for her within it. The clinic was not Dr. Lin's alone anymore. It was theirs.\n",
}

for name, extra in enhancements.items():
    p = BASE / name
    original = p.read_text(encoding="utf-8")
    combined = original.rstrip("\n") + extra
    p.write_text(combined, encoding="utf-8", newline="\n")
    wc = len(combined.split())
    cjk = len(re.findall(r"[\u4e00-\u9fff]", combined))
    print(f"Enhanced {name}: {wc} words, CJK={cjk}")

print()
for fname in sorted(BASE.glob("ch*.txt")):
    txt = fname.read_text(encoding="utf-8")
    wc = len(txt.split())
    cjk = len(re.findall(r"[\u4e00-\u9fff]", txt))
    print(f"{fname.name}: {wc} words, CJK={cjk}")

total = sum(len((BASE / f).read_text(encoding="utf-8").split()) for f in sorted(BASE.glob("ch*.txt")))
print(f"TOTAL: {total} words")
