from pathlib import Path
import re

BASE = Path(r"C:\Users\opc\empire-chronicle\submissions\wattpad-mars-dead\chapters")

expansions = {
    "ch01.txt": "\n\nShe thought of the Founders' stories — the brave ones who had landed on this rusted rock with nothing but willpower and a few tonnes of pressurised steel. Mission videos showed them waving at cameras, their breath visible in the dome air, their eyes bright with the certainty of pioneers. Mission textbooks called it the turning point in human history. Maren had called it a PR campaign. The Founders hadn't been brave, not really. They'd been desperate. Running out of options on a planet that had been dying for centuries.\n\nThe observatory dome had a scratch across the transparency that dated back to the First Storm, a faint white line running from the north edge to the center like a judgement. Maren ran her finger along it occasionally when no one was looking, feeling the roughness of the diamond-glass where the sand had scoured it. It was the only place on Mars where the planet's violence was still visible — every other surface had been repaired, polished, smoothed into compliance. The scratch said: I was here first. I will be here after.\n\nShe pushed off the glass and went to the staff room. The coffee machine was already humming, its interior lights glowing behind the plastic, the pot half-empty from the night shift workers. She poured a fresh cup, added exactly one measure of sweetener, and sat at a table near the window where she could watch the dust storm arrive. It would be here in ninety minutes. The preview screens showed it already — a brown wall moving across the plain with the patience of something that knew it would swallow everything eventually.\n\nMaren had a notebook. It was the only thing she had brought from Earth, the only thing that was truly hers, filled with pressed samples of Martian rock, sketches of mineral formations, and notes written in a handwriting her mother had once said was too precise for a child who wanted to climb mountains. She opened it now, to the last page, and wrote the date: 17 October 2187. Below it, in the margin, she drew a line. A breath mark. Like music. Like waiting.\n",
    "ch06.txt": "\n\nThat evening, Maren went to the observation deck alone. The dome lights were dimmed for the scheduled sleep cycle, and the interior of Elysium looked like a seabed — corridors lit by bioluminescent strips, the suspended gardens glowing green, people moving between the levels like divers in a deep-sea station. The air smelled of artificial lemon and the faint, ever-present mineral tang of the air recyclers.\n\nShe stood at the window for a long time. Outside, the red dust drifted in slow curtains, catching the dome's amber light and making the plain look almost warm, almost habitable. It was a trick of the light. Beneath the surface, the crust was still shifting. Beneath the crust, the mantle was still draining. The planet was dying in slow motion, and the dome was holding, but only barely, only with constant effort, only because twelve thousand people chose to keep the hum going.\n\nMaren thought about Hale in his office, surrounded by schematics and flags and the weight of impossible decisions. She thought about Lira in the medical bay, sorting supplies, counting bandages, preparing for a contingency that would test everything they had. She thought about the families who had boarded the evacuation ships, waving through the viewports, their children pressing hands against the glass, not understanding why they were leaving.\n\nShe thought about Mars — not the dead planet of the textbooks, not the red dot in Earth's sky, but the living thing beneath her feet, still breathing, still trying, still carrying the memory of what it had been. Rivers. Forests. A sky the color of her mother's eyes. All gone now, buried under iron oxide and time, leaving behind only the faintest signatures — a mineral deposit here, a fossilised seed there, the chemical echo of water in a rock sample.\n\nMaren opened her notebook. She drew another breath mark. Then another. Then she wrote a single sentence in the margin: We are the memory of this place now. It is enough.\n",
    "ch07.txt": "\n\nThe descent back to Elysium was quieter than the ascent. The geological team rode in a different rover, their tools stowed, their faces drawn from twelve hours of mapping fractures that looked like wounds. Maren sat beside Lira in the passenger cabin, watching the landscape slide past — the same red dust, the same scarred volcano, the same endless indifference that she had been studying for three years and still could not name.\n\n\"Earth Control wants you to present the Mars Protocol at the Architects' symposium,\" Lira said, breaking the silence. She passed Maren a datapad. The message was short, formal, signed by a diplomat whose name Maren did not recognize. He had asked for a forty-minute presentation, a technical summary, a Q&A session. He had not asked for a story.\n\n\"I'm not a diplomat,\" Maren said.\n\n\"No. But you are the only person who understands what the protocol actually means.\" Lira's voice was gentle, almost amused. \"Do you know what they call it on Luna? The Elysium Miracle. They think we stopped the collapse with a switch. They don't know about the three habitat modules that fell before the Gates went dark. They don't know about the aquifers draining faster every day. They don't know that twelve thousand people are living on borrowed time.\"\n\nMaren nodded. She had been thinking about the gap between what people saw and what was actually happening. The gap was wider on Luna than anywhere else. Luna was wealth, and privilege, and the comfortable distance of people who did not have to watch their world die in real time.\n\n\"I'll go,\" she said.\n\nLira smiled. \"I knew you would.\"\n\nReturning to the ridge the next morning, Maren placed a small stone on the cairn the team had built — a marker for the fracture line, a monument to the slow death of a planet. She touched the rock with both hands. It was cold, smooth, older than the domes, older than the Gates, older than the people who had come to Mars believing they were saving it when all they had ever done was borrow it.\n\nShe thought about the Architects, their Gates, their song across a hundred star systems. They had left behind a legacy of bridges and thefts. They had left behind a species of architects who would inherit their machines and their guilt, who would stand on a dying planet and wonder if survival was a virtue or a wound.\n\nSomewhere in the dark between the stars, the Void Walkers listened. For the first time in two hundred million years, the silence between them was not empty.\n",
}

for name, extra in expansions.items():
    p = BASE / name
    original = p.read_text(encoding="utf-8")
    combined = original.rstrip("\n") + extra
    p.write_text(combined, encoding="utf-8", newline="\n")
    wc = len(combined.split())
    print(f"Expanded {name}: {wc} words")

print()
for fname in sorted(BASE.glob("ch*.txt")):
    txt = fname.read_text(encoding="utf-8")
    wc = len(txt.split())
    cjk = len(re.findall(r"[\u4e00-\u9fff]", txt))
    print(f"{fname.name}: {wc} words, CJK={cjk}")

total = sum(len((BASE / f).read_text(encoding="utf-8").split()) for f in sorted(BASE.glob("ch*.txt")))
print(f"TOTAL: {total} words")
